config/routes.rb
Rails.application.routes.draw do

  root "inspirations#index"

  resources :inspirations

  get '/secret', :to => "inspirations#admin"
  put '/secret', :to => "inspirations#approve"

end

app/models/inspiration.rb
class Inspiration < ActiveRecord::Base

  validates :name, :presence => true
  validates :image, :presence => true
  validates :text, :presence => true
  validates :url, :presence => true

  attr_accessor :image_width, :image_height
  mount_uploader :image, ImageUploader

  # validate :check_dimensions, :on => :create

  # def check_dimensions
  #   if !image_cache.nil? && (image.width < 500 || image.height < 500)
  #     errors.add :image, "must have width of 800px."
  #   end
  # end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/inspirations_controller.rb
class InspirationsController < ApplicationController

  def index
    @inspiration = Inspiration.where(:approved => true).sample
  end

  def new
    @inspiration = Inspiration.new
  end

  def create
    @inspiration = Inspiration.new(inspiration_params)
    @inspiration.save!

    redirect_to inspirations_path, :notice => "You is kind. You is smart. You is important. Your quote will be added shortly!"

  rescue ActiveRecord::RecordInvalid
    render :new
  end

  def show
    @inspiration = Inspiration.find(params[:id])
  end

  def edit
    @inspiration = Inspiration.find(params[:id])
  end

  def update
    @inspiration = Inspiration.find(params[:id])

    @inspiration.attributes = inspiration_params
    @inspiration.save

    redirect_to secret_path, :notice => "Updated inspiration #{params[:id]}"
  end

  def destroy
    @inspiration = Inspiration.find(params[:id])
    @inspiration.destroy

    redirect_to secret_path, :notice => "Deleted inspiration"
  end

  def admin
    @inspirations = Inspiration.all.sort_by { |i| i.name.downcase }
  end

  def approve
    params[:inspiration_approved].each do |id, approved|
      inspiration = Inspiration.find(id)
      inspiration.approved = approved
      inspiration.save
    end

    redirect_to secret_path, :notice => "Updated"
  end

  private

  def inspiration_params
    params.require(:inspiration).permit(:name, :image, :text, :url, :approved)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/inspirations/_error_messages.html.erb
<% if target.errors.any? %>

<div class="alert-form-error">
  <p><strong><%= pluralize(target.errors.count, "error") %> prevented saving your responses:</strong></p>
  <ul>
  <% target.errors.messages.each do |attribute, message| %>
    <li><%= "#{attribute.to_s.humanize} " unless attribute == :publication_orders %><%= message.to_sentence %></li>
  <% end %>
  </ul>
</div>

<% end %>

app/views/inspirations/_form.html.erb
<%= simple_form_for @inspiration, html: { :class => 'form-horizontal' } do |f| %>
  <%= render "error_messages", :target => @inspiration %>
  <%= f.input :name, :label => "Inspiring woman's name" %>
  <%= f.file_field :image, :label => "Image" %>
  <%= f.input :url, :label => "Image source/attribution", :as => :string %>
  <%= f.input :text, :label => "Quote" %>
  <%= f.button :submit, :class => "right" %>
  <%= link_to "Back to all", inspirations_path %>
<% end %>

app/views/inspirations/_item.html.erb
<div class="item">
  <%= image_tag @inspiration.image %>
  <div class="text">
    <h3><%= @inspiration.text %></h3>
    <p>- <%= @inspiration.name %></p>
  </div>
</div>

app/views/inspirations/admin.html.erb
<div class="container-fluid body">
  <div class="col-md-11 space">
    <% if flash[:notice].present?  %>
      <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
    <% end %>
    <%= form_tag nil, :method => "put" do %>
      <table class="table table-striped table-bordered table-hover space">
        <tr class="header">
          <th>ID</th>
          <th>Name</th>
          <th>Quote</th>
          <th>Source</th>
          <th>edit</th>
          <th>delete</th>
          <th>Approved?</th>
        </tr>
        <% @inspirations.each do |inspiration| %>
        <tr>
          <td><%= inspiration.id %></td>
          <td><%= inspiration.name %></td>
          <td><%= inspiration.text %></td>
          <td><%= link_to "URL", inspiration.url %></td>
          <td><%= link_to "Edit", edit_inspiration_path(inspiration) %></td>
          <td><%= link_to "Delete", inspiration_path(inspiration), :method => :delete %></td>
          <td>
            <%= hidden_field_tag "inspiration_approved[#{inspiration.id}]", "0", :id => inspiration.id %>
            <%= check_box_tag "inspiration_approved[#{inspiration.id}]", "1", inspiration.approved?, :id => inspiration.id %>
          </td>
        </tr>
        <% end %>
      </table>
      <%= submit_tag "Save", :class => "btn btn-primary pull-right clear" %>
      <%= link_to "See all", inspirations_path %>
    <% end %>
  </div>
</div>

app/views/inspirations/edit.html.erb
<div class="container-fluid body">
  <div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-6 form-body">
      <h3>Edit inspiration</h3>

      <div class="col-md-12">
        <%= render "form" %>
      </div>
    </div>

    <div class="col-md-3"></div>
  </div>
</div>

<script src="jquery.validate.min.js"></script>

app/views/inspirations/index.html.erb
<div class="container-fluid body">
  <div class="row">
    <div class="col-md-2"></div>

    <% if @inspiration %>
    <div class="col-md-8 show-item">
      <% if flash[:notice].present?  %>
        <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
      <% end %>

      <%= link_to inspiration_path(@inspiration) do %>
        <%= render "item" %>
      <% end %>

      <div class="row links">
        <div class="col-sm-6">
          <%= link_to "See another quote", "/inspirations" %>
        </div>
        <div class="col-sm-6">
          <%= link_to "Add an inspiring quote", new_inspiration_path %>
        </div>
      </div>
    </div>
    <% else %>
    <% end %>

    <div class="col-md-2"></div>
  </div>
</div>

app/views/inspirations/new.html.erb
<div class="container-fluid body">
  <div class="row">
    <div class="col-md-3"></div>

    <div class="col-md-6 form-body">
      <h3>Have a quote you'd like to share?  Add it below.</h3>

      <div class="col-md-12">
        <%= simple_form_for @inspiration, html: { :class => 'form-horizontal' } do |f| %>
          <%= render "error_messages", :target => @inspiration %>
          <%= f.input :name, :label => "Inspiring woman's name" %>
          <%= f.file_field :image, :label => "Image" %>
          <%= f.input :url, :label => "Image source" %>
          <%= f.input :text, :label => "Quote" %>
          <%= f.button :submit, :class => "right" %>
          <%= link_to "back", inspirations_path %>
        <% end %>
      </div>
    </div>

    <div class="col-md-3"></div>
  </div>
</div>

<script src="jquery.validate.min.js"></script>

app/views/inspirations/show.html.erb
<div class="container-fluid body">
  <div class="row">
    <div class="col-md-2"></div>

    <div class="col-md-8 show-item">
      <%= render "item" %>
      <p><%= link_to "Back to all", inspirations_path %></p>
    </div>

    <div class="col-md-2"></div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>StrongAsHell</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
  <!-- Latest compiled and minified CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css">
  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js"></script>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <h1>Females are STRONG AS HELL</h1>

  <%= yield %>

  <br>
  <p class="small" style="text-align:center;">made for you by <%= link_to "@edatrix", "https://about.me/edatrix" %> &copy; 2017</p>
</body>
</html>